name: telegram-alerts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - statsmodels
  - requests
  - pip:
      - telethon # 1.42.0
